### ISSUE TITLE
Sentry SDKs use in other SDKs is not officially supported

### ISSUE THREAD

**Issue by krystofwoldrich** [GetMetaMap/metamap-ios-sdk#41] opened 2023-05-19 09:48 UTC
Sentry and MetaMap customer reported an issue related to `sentry-react-native` and `react-native-metamap-sdk` upon closer inspection it looks like Meta Maps iOS SDK uses Sentry and that's different from the Sentry version the customer installed. This causes the app to crash.

- https://github.com/getsentry/sentry-react-native/issues/3079

One possible solution would be not to remove Sentry from the SDK or guide users to use the same version of the SDK.

Note that Sentry officially doesn't support the use of the SDK in other SDKs. More on the topic [here.](https://github.com/getsentry/sentry-docs/issues/3611) Having Sentry SDK in an app twice can cause issues and errors and also endanger end-user privacy by reporting issues to app developer but also to the SDK dev.

**Comment by 3KINGZ** [comment] 2023-05-22 03:35
> hi @krystofwoldrich . I know about this problem which you mentioned but it's only happening in one client. We integrated Sentry SDK as a private package and it makes it to skip conflict, but in some cases like this, the conflict appears :(

@AvoSukiasyan what do you suggest we do?, this issue is currently preventing us from integrating meta-map on our app

**Comment by AvoSukiasyan** [comment] 2023-05-22 10:48
@3KINGZ can you tell me which Sentry version you use?  I'll add it to my example project, check it, and get back to you.

**Comment by 3KINGZ** [comment] 2023-05-22 14:19
sentry-expo: 4.0.0

**Comment by AvoSukiasyan** [comment] 2023-05-22 15:09
will check and get back to you , thanks @3KINGZ

**Comment by jesuscast** [comment] 2023-06-06 23:35
@AvoSukiasyan we also have this issue. It would be better if Metamap didn't include Sentry.

This forced us to fork the Metamap SDK and remove Sentry manually.

@3KINGZ you can try to use our fork: https://github.com/jesuscast/metamap-ios-sdk

It's stuck in the SDK version 3.12 however.

**Comment by AvoSukiasyan** [comment] 2023-06-08 11:17
Hi @jesuscast. from your commits, I get that you removed sentry files but The Sentry methods from the MetaMap exist and I think the methods are calling your Sentry files. by the way, I fixed the issue and this fix will be included in the next release. I"ll release SDK and get back to you. 
cc: @3KINGZ

**Comment by AvoSukiasyan** [comment] 2023-07-07 15:04
the problem is solved

**Closed** 2023-07-07 15:04 UTC
